plant.config(['$translateProvider', function ($translateProvider) {
    $translateProvider.translations('en', {
        'cancel': 'Cancel',
        'previous': 'Previous',
        'next': 'Next',
        'gohome': 'Back Home',
        'ok': 'Ok',
        'share': 'Share',
        'again': 'Try Again',
        'more': 'Read More',
        'send_success': 'Send Success',
        'send_error': 'Send Failure',
        'menu_aboutus': 'About Us',
        'menu_aboutbrand': 'About Saturdays',
        'menu_plant': 'Succulents & Cactus',
        'menu_pots': 'Pots',
        'menu_problem': 'FAQ',
        'menu_contact': 'Contact Us',
        'menu_ordersearch': 'Order Tracking',
        'menu_gettingstart': 'Getting Start',
        'menu_shopnotice': 'Shopping Notice',
        'menu_service': 'Service',
        'menu_paid': 'Paid Notice',
        'menu_cart': 'Shopping Cart',
        'menu_ordercheckout': 'Order Checkout',
        'menu_emptycrat': 'Your shopping cart is empty.',
        'menu_total': 'Total NT$:',
        'menu_checkout': 'Orders Checkout',
        'menu_follow': 'Follow Us',
        'menu_pottingtutorial': 'Potting Tutorial',
        'menu_takecare': 'Way of maintain',
        'menu_aboutplant': 'About Plants',
        'menu_paymentmethod': 'Payment Method',
        'menu_package': 'Packing / Ship',
        'menu_returnservice': 'Return service',
        'menu_qualitydeclaration': 'Quality Declaration',
        'menu_potcollection': 'Pots Collection',
        'cart_product': 'Product',
        'cart_name': 'Product Name',
        'cart_price': 'Price',
        'cart_amount': 'Amount',
        'cart_total': 'Total',
        'cart_sendway': 'Delivery Method',
        'cart_continue': 'Continue Shopping',
        'cart_putin': 'Add to Cart',
        'cart_processing': 'processing',
        'profile_purchaser': 'Purchaser',
        'profile_name': 'Your Name',
        'profile_mobile': 'Phone Number',
        'profile_email': 'Email',
        'profile_addressee': 'Addressee',
        'profile_as_purchaser': 'Same as Purchaser',
        'profile_address': 'Address',
        'profile_credit': 'Credit Card',
        'profile_paypal': 'Paypal',
        'profile_atm': 'ATM',
        'success_thanks': 'Thank you for your order.',
        'success_ordernumber': 'Order Number',
        'success_bankid': 'SWIFT CODE',
        'success_backaccount': 'Banks Account',
        'success_total': 'Total',
        'success_notice': 'Please complete payment within three days',
        'success_hopelike': 'We hope you like our products',
        'checkout_orderdetail': '1. Order Details',
        'checkout_fillinfo': '2. Fill in the information',
        'checkout_finish': '3. Shopping completed',
        'contact_hassend': 'your message has been send',
        'contact_fastservice': 'We will serve you as soon as possible',
        'contact_male': 'Male',
        'contact_female': 'Female',
        'contact_writedown': 'Write something for us',
        'detail_arrival_notice': 'Arrival Notice',
        'detail_aboutit': 'About it',
        'detail_detail': 'Product detail / Contents',
        'detail_maintain': 'Way of Maintain',
        'detail_water': 'Watering',
        'detail_sun': 'Sunshine',
        'detail_water_way': '・一顆水滴代表一星期澆水一次',
        'detail_relation_product': 'Related Products',
        'error_oops': ' oops! like where an error has occurred! ',
        'error_soon': 'we will deal with your problem immediately later. ',
        'paid_success_title': 'Successful Payment',
        'paid_success_des': ' After checking the information is complete, we will confirm as soon as your payment, please be patient, thank you for your cooperation. ',
        'paid_error_title': 'Sorry .. can not find your order',
        'paid_error_des': 'Your order information is wrong please check , any additional questions, please contact us. ',
        'paid_title': 'Paid Notice',
        'paid_money': 'Remittances Amount(NT$)',
        'paid_account': 'Last five number of your bank account',
        'paid_time': 'Remittances Time',
        'paid_memo': 'Memo',
        'result_title': 'Query Results',
        'result_order_date': 'Order Date',
        'result_product_name': 'Product Name',
        'result_status': 'Processing Status',
        'search_error_title': 'sorry .. can not find the orders',
        'search_error_des': 'please check the order number with the phone number is correct',
        'search_title': 'Order Tracking',
        //YOUNG
        'deliver_foreign': 'Foreign',
        'deliver_taiwan': 'Taiwan',
        'receiver ': 'Receiver',
        'purchaser ': 'Purchaser',
        'page_redirect': 'Page Redirecting...',
        'validation_name_type': 'Name is invalid.',
        'validation_name_empty': 'Name is empty.',
        'validation_phone_type': 'Phone number is invalid',
        'validation_phone_empty': 'Phone number is empty',
        'validation_email_type ': 'E-mail is invalid.',
        'validation_email_empty': 'E-mail is empty.',
        'validation_address_type ': 'Address is invalid',
        'validation_address_empty': 'Address is empty',
        'validation_content_empty ': 'Content is empty',
        'validation_ordernumber_empty ': 'Order-number is invalid',
        'validation_price_empty': 'Price is Empty',
        'validation_price_type': 'Price is invalid',
        'validation_account_type': 'Account is invalid',
        'validation_date_empty': 'Date is invalid',
        'paid': 'Paid',
        'unpaid': 'Unpaid',
        'delivered': 'Delivered',
        'undelivered': 'Undelivered',
        'submit': 'submit',
        'submit_loading': 'loading',
        'submit_success': 'success',
        'submit_fail': 'fail',
        'page_error': 'Page Under Construction',
        'coming_soon': 'Coming Soon'


    });
    $translateProvider.translations('zh-tw', {
        'cancel': '取消',
        'previous': '上一步',
        'next': '下一步',
        'gohome': '回到首頁',
        'ok': '確定',
        'share': '分享',
        'again': '再試一次',
        'more': '瀏覽更多',
        'send_success': '發送成功',
        'send_error': '發送失敗',
        'menu_aboutus': '關於我們',
        'menu_aboutbrand': '關於星期六',
        'menu_plant': '多肉 ＆ 仙人掌',
        'menu_pots': '手工盆器',
        'menu_problem': '常見問題',
        'menu_contact': '聯絡我們',
        'menu_ordersearch': '訂單查詢',
        'menu_gettingstart': '新手教學',
        'menu_shopnotice': '購物須知',
        'menu_service': '售後服務',
        'menu_paid': '通知已付款',
        'menu_cart': '購物車',
        'menu_ordercheckout': '訂單結帳',
        'menu_emptycrat': '您的購物車是空的',
        'menu_total': '總計 NT$',
        'menu_checkout': '訂單結帳',
        'menu_follow': '關注',
        'menu_pottingtutorial': '組盆飄學',
        'menu_takecare': '照顧方式',
        'menu_aboutplant': '關於植物',
        'menu_paymentmethod': '付款方式',
        'menu_package': '包裝 / 寄送',
        'menu_returnservice': '退貨服務',
        'menu_qualitydeclaration': '品質宣言',
        'menu_potcollection': '精選盆器',
        'cart_product': '商品',
        'cart_name': '名稱',
        'cart_price': '單價',
        'cart_amount': '數量',
        'cart_total': '小記',
        'cart_sendway': '寄送方式',
        'cart_continue': '繼續購物',
        'cart_putin': '放入購物車',
        'cart_processing': '處理中',
        'profile_purchaser': '購買人',
        'profile_name': '姓名',
        'profile_mobile': '手機',
        'profile_email': '信箱',
        'profile_addressee': '收件人',
        'profile_as_purchaser': '同購買人',
        'profile_address': '地址',
        'profile_credit': '信用卡',
        'profile_paypal': 'PayPal',
        'profile_atm': 'ATM轉帳',
        'success_thanks': '感謝您的訂購',
        'success_ordernumber': '訂單編號',
        'success_bankid': '銀行代號',
        'success_backaccount': '匯款帳號',
        'success_total': '結帳金額',
        'success_notice': '請於三日內完成匯款',
        'success_hopelike': '希望您喜歡我們的產品',
        'checkout_orderdetail': '1.訂單明細',
        'checkout_fillinfo': '2.填寫資料',
        'checkout_finish': '3.購物完成',
        'contact_hassend': '您的訊息已經為您送出',
        'contact_fastservice': '我們將盡快為您服務',
        'contact_male': '男士',
        'contact_female': '女士',
        'contact_writedown': '寫點東西給我們吧',
        'detail_arrival_notice': '到貨通知',
        'detail_aboutit': '關於他',
        'detail_detail': '產品規格 / 內容物',
        'detail_maintain': '養護方式',
        'detail_water': '澆水',
        'detail_sun': '陽光',
        'detail_water_way': '・一顆水滴代表一星期澆一次水，以此類推',
        'detail_relation_product': '相關產品',
        'error_oops': 'Oops！ 好像哪裏發生錯誤了 ！',
        'error_soon': '稍後我們會立即處理您的問題。',
        'paid_success_title': '通知付款成功',
        'paid_success_des': '核對資料完成後，我們會盡快確認您的匯款，請耐心等候，謝謝您的配合。',
        'paid_error_title': 'Sorry..找不到您的訂單',
        'paid_error_des': '請核對您的訂單資訊是否有誤，如有其他問題，歡迎聯絡我們。',
        'paid_title': '通知已付款',
        'paid_money': '匯款金額',
        'paid_account': '帳號後五碼',
        'paid_time': '匯款時間',
        'paid_memo': '備註',
        'result_title': '查詢結果',
        'result_order_date': '訂購日期',
        'result_product_name': '產品名稱',
        'result_status': '處理狀態',
        'search_error_title': 'Sorry..找不到訂單',
        'search_error_des': '請檢查訂單編號跟手機號碼是否錯誤',
        'search_title': '訂單查詢',
        //YOUNG
        'deliver_foreign': '離島寄送',
        'deliver_taiwan': '本島寄送',
        'receiver ': '收件人',
        'purchaser ': '購買人',
        'page_redirect': '頁面重新導向中...',
        'validation_name_type': '姓名格式錯誤',
        'validation_name_empty': '姓名不得為空',
        'validation_phone_type': '手機格式錯誤',
        'validation_phone_empty': '手機不得為空',
        'validation_email_type ': '電子信箱格式錯誤',
        'validation_email_empty': '電子信箱不得為空',
        'validation_address_type ': '地址格式錯誤',
        'validation_address_empty': '地址不得為空',
        'validation_content_empty ': '內容不得為空',
        'validation_ordernumber_empty ': '訂單編號不得為空',
        'validation_price_empty': '金額不得為空',
        'validation_price_type': '金額格式錯誤',
        'validation_account_type': '帳號長度錯誤',
        'validation_date_empty': '日期錯誤',
        'paid': '已付款',
        'unpaid': '未付款',
        'delivered': '已出貨',
        'undelivered': '未出貨',
        'submit': '送出',
        'submit_loading': '處理中',
        'submit_success': '傳送成功',
        'submit_fail': '傳送成功',
        'page_error': '施工中...',
        'coming_soon': '敬請期待',

    });

    var userLang = (navigator.language || navigator.userLanguage).toLocaleLowerCase();
    switch (userLang) {
        case 'zh-tw':
            $translateProvider.preferredLanguage('zh-tw');
            //$translateProvider.preferredLanguage('en');
            break;
        case 'en':
            $translateProvider.preferredLanguage('en');
            break;
        default:
            $translateProvider.preferredLanguage('en');
            break;
    }
}]);
